2023-09-29 21:15:50,139 ERROR: Exception on /login [POST] [in /Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/app/routes.py", line 55, in login
    if user is None or not user.check_password(form.password.data):
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/app/models.py", line 38, in check_password
    return check_password_hash(self.password_hash, password)
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/werkzeug/security.py", line 135, in check_password_hash
    method, salt, hashval = pwhash.split("$", 2)
AttributeError: 'NoneType' object has no attribute 'split'
2023-09-29 21:15:58,132 ERROR: Exception on /login [POST] [in /Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/app/routes.py", line 55, in login
    if user is None or not user.check_password(form.password.data):
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/app/models.py", line 38, in check_password
    return check_password_hash(self.password_hash, password)
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/werkzeug/security.py", line 135, in check_password_hash
    method, salt, hashval = pwhash.split("$", 2)
AttributeError: 'NoneType' object has no attribute 'split'
2023-09-29 21:16:04,684 ERROR: Exception on /login [POST] [in /Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/app/routes.py", line 55, in login
    if user is None or not user.check_password(form.password.data):
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/app/models.py", line 38, in check_password
    return check_password_hash(self.password_hash, password)
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/werkzeug/security.py", line 135, in check_password_hash
    method, salt, hashval = pwhash.split("$", 2)
AttributeError: 'NoneType' object has no attribute 'split'
2023-09-29 21:36:52,501 INFO: Microblog startup [in /Users/artem/Documents/Programming/Python/Flask-micro-blog/app/__init__.py:48]
2023-10-01 01:46:56,216 INFO: Microblog startup [in /Users/artem/Documents/Programming/Python/Flask-micro-blog/app/__init__.py:50]
2023-10-02 16:14:30,149 INFO: Microblog startup [in /Users/artem/Documents/Programming/Python/Flask-micro-blog/app/__init__.py:50]
2023-10-03 00:44:40,771 INFO: Microblog startup [in /Users/artem/Documents/Programming/Python/Flask-micro-blog/app/__init__.py:55]
2023-10-03 01:21:40,881 INFO: Microblog startup [in /Users/artem/Documents/Programming/Python/Flask-micro-blog/app/__init__.py:55]
2023-10-03 01:21:53,524 INFO: Microblog startup [in /Users/artem/Documents/Programming/Python/Flask-micro-blog/app/__init__.py:55]
2023-10-03 01:22:16,467 INFO: Microblog startup [in /Users/artem/Documents/Programming/Python/Flask-micro-blog/app/__init__.py:55]
2023-10-03 01:22:21,569 ERROR: Exception on / [GET] [in /Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/app/routes.py", line 40, in index
    return render_template('index.html',
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/app/templates/index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/app/templates/base.html", line 51, in top-level template code
    {% block content %}
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/app/templates/index.html", line 19, in block 'content'
    {% include '_post.html' %}
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/app/templates/_post.html", line 16, in top-level template code
    '{{ g.locale }}');>{{ _('Translate') }}</a>
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/jinja2/ext.py", line 167, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/jinja2/ext.py", line 173, in gettext
    rv = __context.call(func, __string)
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask_babel/__init__.py", line 109, in <lambda>
    lambda x: get_translations().ugettext(x),
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask_babel/__init__.py", line 209, in get_translations
    return get_domain().get_translations()
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask_babel/__init__.py", line 554, in get_translations
    locale = get_locale()
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/venv/lib/python3.8/site-packages/flask_babel/__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "/Users/artem/Documents/Programming/Python/Flask-micro-blog/app/__init__.py", line 59, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: name 'request' is not defined
